import type { ReportData } from "@/types";

self.onmessage = (e: MessageEvent) => {
  if (e.data.type !== "RENDER") return;

  const data: ReportData = e.data.data;
  const { engagement, map_totals, custom_vars } = data;

  const fmtCur = (v: number) =>
    new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: engagement.currency,
      minimumFractionDigits: 2,
    }).format(Math.abs(v));

  const row = (label: string, current: number, prior: number, bold = false) => `
    <tr class="${bold ? "subtotal" : ""}">
      <td class="label">${label}</td>
      <td class="amount ${current < 0 ? "neg" : ""}">${current < 0 ? `(${fmtCur(current)})` : fmtCur(current)}</td>
      <td class="amount ${prior < 0 ? "neg" : ""}">${prior < 0 ? `(${fmtCur(prior)})` : fmtCur(prior)}</td>
    </tr>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>${engagement.entity_name} — Financial Statements</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; font-size: 12px; color: #000; margin: 40px; }
  h1 { font-size: 16px; margin-bottom: 2px; }
  .subtitle { color: #555; font-size: 11px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 32px; }
  th { border-bottom: 2px solid #000; padding: 4px 8px; text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: .05em; }
  th.amount, td.amount { text-align: right; font-family: monospace; }
  td { padding: 3px 8px; border-bottom: 1px solid #ddd; }
  tr.subtotal td { border-top: 2px solid #000; font-weight: 700; }
  .neg { color: #c00; }
  .label { width: 60%; }
</style>
</head>
<body>
  <h1>${engagement.entity_name}</h1>
  <div class="subtitle">Year Ended ${engagement.year_end} — ${engagement.currency}</div>

  <table>
    <thead>
      <tr>
        <th class="label">Map Number</th>
        <th class="amount">Current Year (Adj)</th>
        <th class="amount">Prior Year</th>
      </tr>
    </thead>
    <tbody>
      ${map_totals.map((m) => row(
        `${m.map_number} — ${m.label}`,
        m.adjusted_current,
        m.prior_total
      )).join("")}
    </tbody>
  </table>

  ${custom_vars.length > 0 ? `
  <h2 style="font-size:13px;margin-bottom:8px;">Custom Variables</h2>
  <table>
    <thead><tr><th>Key</th><th>Value</th><th>Description</th></tr></thead>
    <tbody>
      ${custom_vars.map((v) => `<tr><td class="mono">${v.key}</td><td>${v.value}</td><td style="color:#555">${v.description ?? ""}</td></tr>`).join("")}
    </tbody>
  </table>` : ""}

  <div style="font-size:10px;color:#999;margin-top:40px;border-top:1px solid #ddd;padding-top:8px;">
    Generated by Worked Papers — ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;

  self.postMessage({ type: "RENDERED", html });
};
